compile_pdf:
  script:
    - make 
  artifacts:
    paths:
      - main.pdf
  after_script:
    - export GITHUB_TOKEN=$GITHUB_THEWESCH_ROADSTER_DOC_TOKEN 
    - ghr "v.0.$CI_BUILD_ID" main.pdf