compile_pdf:
  script:
    - make 
  artifacts:
    paths:
      - main.pdf
  after_script:
    - ghr -t $GITHUB_THEWESCH_ROADSTER_DOC_TOKEN -u thewesch -r ba-roadster-doc "v.0.$CI_BUILD_ID" main.pdf