compile_pdf:
  script:
    - make 
  artifacts:
    paths:
      - main.pdf
  after_script:
    - echo $CI_BUILD_ID
    - sudo ./release_to_github.sh $CI_BUILD_ID $GITHUB_THEWESCH_ROADSTER_DOC_TOKEN